### ISSUE TITLE
Question: compatibility with get/set properties

### ISSUE THREAD

**Issue by IlCallo** [PSanetra/bind-observable#5]
Giving the fact that the original property is deleted to create the new one using an accessor descriptor upon the ReplaySubject, I guess that this decorator cannot be applied to a property which is already defined as a get/set couple, right?

If not, and there is not solution against it, I'd probably  specify it in the README

**Comment by IlCallo** [comment]
**EDIT**
I managed to make it work.
It was a problem of context, as explained in the updated code below.
Feel free to copy the mechanism if you want to make your Decorator _accessor-friendly_.
Currently I'm forced to use my decorator before yours like this

```typescript
  @Input()
  @CoerceBoolean()
  @BindObservable()
  private property = false;
  private property$!: Observable<boolean>;
```

but it would be nice to be able to put it in any order without thinking about it.

-------------------

To give you more context, I'm trying to create a Decorator which removes the original property like your bind-observable and manages to keep the decorator chain alive avoid breaking other decorators.

```typescript
import { coerceBooleanProperty } from '@angular/cdk/coercion';

/**
 * Cooerce the property to boolean.
 * @param {string} observableKey
 * optional custom key of the shadow property.
 * If not provided, the shadowPropertyName is the name of the original property key with a '_' prefix.
 * If a property with the same name as shadowPropertyName already exists, it will be deleted.
 */
export function CoerceBoolean(shadowPropertyKey?: string) {
  // Third parameter (descriptor) is passed only if the decorated property is an accessor one.
  //  See Property Decorators at https://www.typescriptlang.org/docs/handbook/decorators.html
  // Because of this, we are forced to retrieve the current descriptor with Reflection API
  return (target: any, propertyKey: string) => {
    shadowPropertyKey = shadowPropertyKey || '_' + propertyKey;

    const descriptor = Reflect.getOwnPropertyDescriptor(target, propertyKey);

    delete target[propertyKey];
    delete target[shadowPropertyKey];

    if (!descriptor) {
      Object.defineProperty(target, shadowPropertyKey, {
        // Always false by default
        value: false,
        writable: true
      });

      Object.defineProperty(target, propertyKey, {
        configurable: true,
        set(value) {
          this[shadowPropertyKey as string] = coerceBooleanProperty(value);
        },
        get(): boolean {
          return this[shadowPropertyKey as string];
        }
      });
    } else {
      // TODO when taking in a property based on accessors we don't have a way to automatically resolve a 'not explictly defined' to a false and this causes problems. Find a way to manage this if possible

      // The 'this' variable is bound to the instantiation context (this decorator in this case),
      //  while decorator spec says that the context inside getters and setters
      //  must be the object containing the property.
      // To comply to the spec we must use 'call' when using accessor descriptor methods
      //  and pass by the current context because the underlying decorator
      //  could be using the 'this' in its getter/setters.
      Object.defineProperty(target, propertyKey, {
        configurable: true,
        set(value) {
          if (!descriptor.set) {
            throw new Error(`Property ${propertyKey} doesn't have a setter and cannot be written`);
          }

          descriptor.set.call(this, coerceBooleanProperty(value));
        },
        get(): boolean {
          if (!descriptor.get) {
            throw new Error(`Property ${propertyKey} doesn't have a getter and cannot be read`);
          }

          return descriptor.get.call(this);
        }
      });
    }
  };
}
```

This works for what I want to accomplish, but I'm trying to make it work nicely with your Decorator.
Problem is, we both "destroy" the original property and then create an accessor property in its place.
I tried to overcome this by retrieving the descriptor of the current property before destroying it and then executing the setter and getter of the original accessor descriptor, but it doesn't seem to work nice for some reason.

**Comment by IlCallo** [comment]
@PSanetra ping?

**Comment by PSanetra** [comment]
@IlCallo In version 1.0.2 the decorator should not break other decorators anymore, but there are still issues when you use this decorator directly on property accessors in a class.

There are excluded tests which are still failing: https://github.com/PSanetra/bind-observable/blob/4a4aedda6f9729dad89eb435647a183ab16842fd/src/bind-observable.spec.ts#L56-L123

**Comment by IlCallo** [comment]
Well, it's an advancement anyway, ty! :)

Also, I never thought it was possible to use @BindObservable to a getter+setter couple, is it an expected use case?
You should probably put a disclaimer in README about this special case (or an example, when/if it works)

**Comment by PSanetra** [comment]
I think it could be a rare use case. I have documented this behavior in a `Known Bugs` section in the README file.

**Comment by IlCallo** [comment]
Ehy @PSanetra , today I was still playing around with your decorator and I noticed that in some cases it doesn't work with underlying accessors because you forgot to bind the `this` to a certain `.get()` call at this line.

https://github.com/PSanetra/bind-observable/blob/259bff87cc10ae0644729cd8cb38a215399ed7e1/src/bind-observable.ts#L87

Is it on purpose for some reason? Can you update it like in this line

https://github.com/PSanetra/bind-observable/blob/259bff87cc10ae0644729cd8cb38a215399ed7e1/src/bind-observable.ts#L95

and check if everything still works?

**Comment by PSanetra** [comment]
@IlCallo Nice catch! I have released a new version which addresses that issue.
